# Generated by Django 4.0 on 2021-12-19 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('livre_dor', '0002_alter_card_model_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_model',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user'),
        ),
    ]
